# Generated by Django 5.2.11 on 2026-03-02 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_family', models.CharField(choices=[('cactus', 'Cactus & Succulents'), ('tropical', 'Tropical Foliage'), ('ferns', 'Ferns & Leafy Greens'), ('flowering', 'Flowering Plants'), ('palms', 'Palms & Trees'), ('air', 'Air Plants & Moss'), ('other', 'Other')], max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('water', 'Watered'), ('sunlight', 'Sunlight')], max_length=20)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
        ),
    ]
