# Generated by Django 5.2.11 on 2026-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelog',
            name='date_logged',
            field=models.DateTimeField(),
        ),
    ]
